version: '3'

services:
  spring:
    image: adoptopenjdk/openjdk8
    container_name: questionnaire-api-server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./build/libs/geek-questionnaire-0.0.1-SNAPSHOT.jar:/home/app.jar
    entrypoint: ["java", "-jar", "/home/app.jar"]
  db:
    image: mysql:8.0
    container_name: questionnaire-api-database
    restart: unless-stopped
    volumes:
      - questionnaire-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  questionnaire-db: {}